name: CI

on:
  push:
    branches: [lesson*]
  pull_request:
    branches: [lesson*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with gradle
        run: ./gradlew build