name: CI

on:
  push:
    branches: [lesson*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 6.0

      - name: Build with gradle
        run: ./gradlew build --warning-mode all

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: build/reports/**